# Allow build scripts for trusted dependencies
# - https://pnpm.io/settings#allowbuilds
allowBuilds:
  # unrs-resolver postinstall only required for npm <v11 bug
  # - https://github.com/unrs/unrs-resolver/issues/85#issuecomment-3435918759
  unrs-resolver: false

# Prevent installation of packages newer than 7 days
# to mitigate supply chain risks
# - https://pnpm.io/settings#minimumreleaseage
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - '@upleveled/*'
  - eslint-config-upleveled
  - stylelint-config-upleveled
  # Renovate security update: next@16.1.5 || 16.2.6 || 16.2.11
  - next@16.1.5 || 16.2.6 || 16.2.11
  # Renovate security update: postcss@8.5.10 || 8.5.18 || 8.5.23
  - postcss@8.5.10 || 8.5.18 || 8.5.23

overrides:
  '@types/react': 19.2.18
  '@types/react-dom': 19.2.5
